### ISSUE TITLE
gpfdist error

### ISSUE THREAD

**Issue by chentao1994** [vitessedata/issues#1]
[gpfdist_error.zip](https://github.com/vitessedata/issues/files/2338636/gpfdist_error.zip)

**Comment by cktan** [comment]
@chentao1994 please provide the output of:

select version();
show vitesse.version;

**Comment by chentao1994** [comment]
version: vitesse.deepgreendb.16.25.180201

**Comment by cktan** [comment]
Please see if it can be repro on the latest 16.32

**Comment by chentao1994** [comment]
The same ERROR

**Comment by chentao1994** [comment]
[dp@ldw2 dp]$ ll
总用量 364348
-rw-r--r--  1 dp dp         5 8月  31 14:04 all_host
lrwxrwxrwx  1 dp dp        33 8月  31 11:51 deepgreendb -> /data/dp/deepgreendb.16.32.180829
drwxr-xr-x 17 dp dp      4096 8月  31 11:51 deepgreendb.16.32.180829
-rw-r--r--  1 dp dp 373071293 8月  31 11:49 deepgreendb.16.32.rh6.x86_64.180829.bin
drwxr-xr-x  4 dp dp      4096 8月  31 14:04 dpdata
-rw-rw-r--  1 dp dp      2605 8月  31 14:16 gpinitsystem_config
[dp@ldw2 dp]$ psql -d postgres -p 3636
psql (8.2.15)
Type "help" for help.

postgres=# select * from ext_aa1 ;
ERROR:  Error on receive from seg0 slice1 ldw2:40010 pid=29287: server closed the connection unexpectedly
DETAIL:  
	This probably means the server terminated abnormally
	before or while processing the request.
ERROR:  could not temporarily connect to one or more segments (cdbgang.c:2457)
postgres=# select version();
                                                                                            version                                                                                            
-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 PostgreSQL 8.2.15 (Greenplum Database 4.3.99.00 build Deepgreen TDB) on x86_64-unknown-linux-gnu, compiled by GCC gcc (GCC) 6.3.1 20170216 (Red Hat 6.3.1-3) compiled on Aug 30 2018 00:13:25
(1 row)

**Comment by vitesse-ftian** [comment]
Fixed, please wait for a new release.

The included data, test.csv, is interesting.   Its last line does not have an ending \n.    We more or less parsed it OK, but somehow we padded an extra \n into the result.   I will fix later.

For now, please make sure the last line ends with \n.

**Comment by chentao1994** [comment]
If ending with \n, a row of empty data will be read when reading data.

**Comment by vitesse-ftian** [comment]
Quote: If ending with \n, a row of empty data will be read when reading data.
No, this is not true.

Last line without EOL is fixed anyway.
